title: Cameron Ball
email: hi@camball.me
description: Portfolio/Blog
url: https://camball.me
meta_author: Cameron Ball

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
