# Site settings
title: Cameron Ball
email: im.cameron@pm.me
url: https://camball.github.io
description: Portfolio/Blog
keywords: ""
subtitle: Internet Head-Scratcher
meta_author: Ball Cam

# Footer settings
footer:
  copyright: Cam Ball

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-data
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
