title: Cameron Ball
email: im.cameron@proton.me
description: Portfolio/Blog
url: https://camballsoup.dev
meta_author: Cameron Ball

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
